# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 748)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.camera = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera.sizePolicy().hasHeightForWidth())
        self.camera.setSizePolicy(sizePolicy)
        self.camera.setObjectName("camera")
        self.horizontalLayout_4.addWidget(self.camera)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(9, -1, 9, -1)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_current_hangle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_hangle.setFont(font)
        self.label_current_hangle.setObjectName("label_current_hangle")
        self.verticalLayout_2.addWidget(self.label_current_hangle)
        self.label_current_vangle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_vangle.setFont(font)
        self.label_current_vangle.setObjectName("label_current_vangle")
        self.verticalLayout_2.addWidget(self.label_current_vangle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.cameratabs = QtWidgets.QTabWidget(self.centralwidget)
        self.cameratabs.setObjectName("cameratabs")
        self.tabcamworker = QtWidgets.QWidget()
        self.tabcamworker.setObjectName("tabcamworker")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabcamworker)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.tabcamworker)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label = QtWidgets.QLabel(self.tabcamworker)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.tabcamworker)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.camera_slide2 = QtWidgets.QSlider(self.tabcamworker)
        self.camera_slide2.setMinimum(1)
        self.camera_slide2.setMaximum(100)
        self.camera_slide2.setProperty("value", 50)
        self.camera_slide2.setOrientation(QtCore.Qt.Horizontal)
        self.camera_slide2.setObjectName("camera_slide2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.camera_slide2)
        self.camera_slide1 = QtWidgets.QSlider(self.tabcamworker)
        self.camera_slide1.setMinimum(1)
        self.camera_slide1.setMaximum(100)
        self.camera_slide1.setProperty("value", 50)
        self.camera_slide1.setOrientation(QtCore.Qt.Horizontal)
        self.camera_slide1.setObjectName("camera_slide1")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.camera_slide1)
        self.camera_slide3 = QtWidgets.QSlider(self.tabcamworker)
        self.camera_slide3.setMinimum(1)
        self.camera_slide3.setMaximum(100)
        self.camera_slide3.setProperty("value", 50)
        self.camera_slide3.setOrientation(QtCore.Qt.Horizontal)
        self.camera_slide3.setObjectName("camera_slide3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.camera_slide3)
        self.label_4 = QtWidgets.QLabel(self.tabcamworker)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.camera_slide4 = QtWidgets.QSlider(self.tabcamworker)
        self.camera_slide4.setProperty("value", 50)
        self.camera_slide4.setOrientation(QtCore.Qt.Horizontal)
        self.camera_slide4.setObjectName("camera_slide4")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.camera_slide4)
        self.label_5 = QtWidgets.QLabel(self.tabcamworker)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.camera_slide5 = QtWidgets.QSlider(self.tabcamworker)
        self.camera_slide5.setProperty("value", 50)
        self.camera_slide5.setOrientation(QtCore.Qt.Horizontal)
        self.camera_slide5.setObjectName("camera_slide5")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.camera_slide5)
        self.label_6 = QtWidgets.QLabel(self.tabcamworker)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.camera_slide6 = QtWidgets.QSlider(self.tabcamworker)
        self.camera_slide6.setProperty("value", 50)
        self.camera_slide6.setOrientation(QtCore.Qt.Horizontal)
        self.camera_slide6.setObjectName("camera_slide6")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.camera_slide6)
        self.label_7 = QtWidgets.QLabel(self.tabcamworker)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.camera_slide7 = QtWidgets.QSlider(self.tabcamworker)
        self.camera_slide7.setOrientation(QtCore.Qt.Horizontal)
        self.camera_slide7.setObjectName("camera_slide7")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.camera_slide7)
        self.label_8 = QtWidgets.QLabel(self.tabcamworker)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.camera_slide8 = QtWidgets.QSlider(self.tabcamworker)
        self.camera_slide8.setOrientation(QtCore.Qt.Horizontal)
        self.camera_slide8.setObjectName("camera_slide8")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.camera_slide8)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.camera_check1 = QtWidgets.QCheckBox(self.tabcamworker)
        self.camera_check1.setObjectName("camera_check1")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.camera_check1)
        self.camera_check2 = QtWidgets.QCheckBox(self.tabcamworker)
        self.camera_check2.setObjectName("camera_check2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.camera_check2)
        self.camera_check3 = QtWidgets.QCheckBox(self.tabcamworker)
        self.camera_check3.setObjectName("camera_check3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.camera_check3)
        self.camera_check4 = QtWidgets.QCheckBox(self.tabcamworker)
        self.camera_check4.setObjectName("camera_check4")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.camera_check4)
        self.camera_check5 = QtWidgets.QCheckBox(self.tabcamworker)
        self.camera_check5.setObjectName("camera_check5")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.camera_check5)
        self.camera_check6 = QtWidgets.QCheckBox(self.tabcamworker)
        self.camera_check6.setObjectName("camera_check6")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.camera_check6)
        self.camera_combo1 = QtWidgets.QComboBox(self.tabcamworker)
        self.camera_combo1.setObjectName("camera_combo1")
        self.camera_combo1.addItem("")
        self.camera_combo1.addItem("")
        self.camera_combo1.addItem("")
        self.camera_combo1.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.camera_combo1)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.cameratabs.addTab(self.tabcamworker, "")
        self.tabcamera0 = QtWidgets.QWidget()
        self.tabcamera0.setObjectName("tabcamera0")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabcamera0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtWidgets.QLabel(self.tabcamera0)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.cam0_brightness = QtWidgets.QSlider(self.tabcamera0)
        self.cam0_brightness.setProperty("value", 50)
        self.cam0_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.cam0_brightness.setObjectName("cam0_brightness")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cam0_brightness)
        self.label_10 = QtWidgets.QLabel(self.tabcamera0)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.cam0_contrast = QtWidgets.QSlider(self.tabcamera0)
        self.cam0_contrast.setProperty("value", 50)
        self.cam0_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.cam0_contrast.setObjectName("cam0_contrast")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cam0_contrast)
        self.label_11 = QtWidgets.QLabel(self.tabcamera0)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.cam0_exposure = QtWidgets.QSlider(self.tabcamera0)
        self.cam0_exposure.setProperty("value", 50)
        self.cam0_exposure.setOrientation(QtCore.Qt.Horizontal)
        self.cam0_exposure.setObjectName("cam0_exposure")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cam0_exposure)
        self.label_12 = QtWidgets.QLabel(self.tabcamera0)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.cam0_gain = QtWidgets.QSlider(self.tabcamera0)
        self.cam0_gain.setProperty("value", 50)
        self.cam0_gain.setOrientation(QtCore.Qt.Horizontal)
        self.cam0_gain.setObjectName("cam0_gain")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cam0_gain)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.cameratabs.addTab(self.tabcamera0, "")
        self.tabcamera1 = QtWidgets.QWidget()
        self.tabcamera1.setObjectName("tabcamera1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tabcamera1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tabcamera1)
        self.label_13.setObjectName("label_13")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.horizontalSlider_7 = QtWidgets.QSlider(self.tabcamera1)
        self.horizontalSlider_7.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_7.setObjectName("horizontalSlider_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_7)
        self.label_14 = QtWidgets.QLabel(self.tabcamera1)
        self.label_14.setObjectName("label_14")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.horizontalSlider_8 = QtWidgets.QSlider(self.tabcamera1)
        self.horizontalSlider_8.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_8.setObjectName("horizontalSlider_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_8)
        self.label_15 = QtWidgets.QLabel(self.tabcamera1)
        self.label_15.setObjectName("label_15")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.horizontalSlider_9 = QtWidgets.QSlider(self.tabcamera1)
        self.horizontalSlider_9.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_9.setObjectName("horizontalSlider_9")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_9)
        self.label_16 = QtWidgets.QLabel(self.tabcamera1)
        self.label_16.setObjectName("label_16")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.horizontalSlider_10 = QtWidgets.QSlider(self.tabcamera1)
        self.horizontalSlider_10.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_10.setObjectName("horizontalSlider_10")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_10)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.cameratabs.addTab(self.tabcamera1, "")
        self.verticalLayout.addWidget(self.cameratabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cameratabs.setCurrentIndex(0)
        self.camera_combo1.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_current_hangle.setText(_translate("MainWindow", "HANGLE 000"))
        self.label_current_vangle.setText(_translate("MainWindow", "VANGLE 000"))
        self.label_3.setText(_translate("MainWindow", "Border Thr"))
        self.label.setText(_translate("MainWindow", "Mark Thre"))
        self.label_2.setText(_translate("MainWindow", "Mark Blur"))
        self.label_4.setText(_translate("MainWindow", "Border Blur"))
        self.label_5.setText(_translate("MainWindow", "Block Size"))
        self.label_6.setText(_translate("MainWindow", "K Size"))
        self.label_7.setText(_translate("MainWindow", "K Quality"))
        self.label_8.setText(_translate("MainWindow", "Max Area"))
        self.camera_check1.setText(_translate("MainWindow", "Invert"))
        self.camera_check2.setText(_translate("MainWindow", "CheckBox"))
        self.camera_check3.setText(_translate("MainWindow", "CheckBox"))
        self.camera_check4.setText(_translate("MainWindow", "CheckBox"))
        self.camera_check5.setText(_translate("MainWindow", "CheckBox"))
        self.camera_check6.setText(_translate("MainWindow", "CheckBox"))
        self.camera_combo1.setItemText(0, _translate("MainWindow", "Color Image"))
        self.camera_combo1.setItemText(1, _translate("MainWindow", "Gray Image"))
        self.camera_combo1.setItemText(2, _translate("MainWindow", "Smooth Marks"))
        self.camera_combo1.setItemText(3, _translate("MainWindow", "Smooth Borders"))
        self.cameratabs.setTabText(self.cameratabs.indexOf(self.tabcamworker), _translate("MainWindow", "Adjust"))
        self.label_9.setText(_translate("MainWindow", "Brightness"))
        self.label_10.setText(_translate("MainWindow", "Contrast"))
        self.label_11.setText(_translate("MainWindow", "Exposure"))
        self.label_12.setText(_translate("MainWindow", "Gain"))
        self.cameratabs.setTabText(self.cameratabs.indexOf(self.tabcamera0), _translate("MainWindow", "Camera 0"))
        self.label_13.setText(_translate("MainWindow", "Brightness"))
        self.label_14.setText(_translate("MainWindow", "Contrast"))
        self.label_15.setText(_translate("MainWindow", "Exposure"))
        self.label_16.setText(_translate("MainWindow", "Gain"))
        self.cameratabs.setTabText(self.cameratabs.indexOf(self.tabcamera1), _translate("MainWindow", "Camera 1"))

